apiVersion: v1
kind: Secret
metadata:
  name:  chatapp-secrets
  namespace: chat-app
type: Opaque
data:
  JWT: ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKU2IyeGxJam9pUVdSdGFXNGlMQ0pKYzNOMVpYSWlPaUpKYzNOMVpYSWlMQ0pWYzJWeWJtRnRaU0k2SWtwaGRtRkpibFZ6WlNJc0ltVjRjQ0k2TVRjNE5UVTROVGcwTkN3aWFXRjBJam94TnpnMU5UZzFPRFEwZlEucy1vLWtSTjA3Q29VWTlkRG5Dc3pGU0ZHMVFXQzZNUWJLblRLOFphTlZVYwo=
